USE [motrpac]
GO

/****** Object:  Table [dbo].[frm_RESL]    Script Date: 9/24/2018 5:03:44 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[frm_RESL](
	[rec_id] [int] IDENTITY(1,1) NOT NULL,
	[recordthread] [varchar](50) NOT NULL,
	[d_inserted] [datetime] NOT NULL,
	[insertedBy] [varchar](50) NOT NULL,
	[deleted] [int] NULL,
	[deleteReason] [varchar](max) NULL,
	[participantGUID] [varchar](50) NULL,
	[visitGUID] [varchar](50) NULL,
	[d_visit] [date] NULL,
	[staffID] [nvarchar](4) NULL,
	[abs_machine] [varchar](max) NULL,
	[abs_manufacture] [varchar](50) NULL,
	[abs_setting1] [int] NULL,
	[abs_setting1guid] [varchar](50) NULL,
	[abs_setting1na] [int] NULL,
	[abs_setting2] [int] NULL,
	[abs_setting2guid] [varchar](50) NULL,
	[abs_setting2na] [int] NULL,
	[abs_setting3] [int] NULL,
	[abs_setting3guid] [varchar](50) NULL,
	[abs_setting3na] [int] NULL,
	[abs_setting4] [int] NULL,
	[abs_setting4guid] [varchar](50) NULL,
	[abs_setting4na] [int] NULL,
	[bicep_machine] [varchar](max) NULL,
	[bicep_manufacture] [varchar](50) NULL,
	[bicep_setting1] [int] NULL,
	[bicep_setting1guid] [varchar](50) NULL,
	[bicep_setting1na] [int] NULL,
	[bicep_setting2] [int] NULL,
	[bicep_setting2guid] [varchar](50) NULL,
	[bicep_setting2na] [int] NULL,
	[bicep_setting3] [int] NULL,
	[bicep_setting3guid] [varchar](50) NULL,
	[bicep_setting3na] [int] NULL,
	[bicep_setting4] [int] NULL,
	[bicep_setting4guid] [varchar](50) NULL,
	[bicep_setting4na] [int] NULL,
	[calf_machine] [varchar](max) NULL,
	[calf_manufacture] [varchar](50) NULL,
	[calf_setting1] [int] NULL,
	[calf_setting1guid] [varchar](50) NULL,
	[calf_setting1na] [int] NULL,
	[calf_setting2] [int] NULL,
	[calf_setting2guid] [varchar](50) NULL,
	[calf_setting2na] [int] NULL,
	[calf_setting3] [int] NULL,
	[calf_setting3guid] [varchar](50) NULL,
	[calf_setting3na] [int] NULL,
	[calf_setting4] [int] NULL,
	[calf_setting4guid] [varchar](50) NULL,
	[calf_setting4na] [int] NULL,
	[chest_machine] [varchar](max) NULL,
	[chest_manufacture] [varchar](50) NULL,
	[chest_setting1] [int] NULL,
	[chest_setting1guid] [varchar](50) NULL,
	[chest_setting1na] [int] NULL,
	[chest_setting2] [int] NULL,
	[chest_setting2guid] [varchar](50) NULL,
	[chest_setting2na] [int] NULL,
	[chest_setting3] [int] NULL,
	[chest_setting3guid] [varchar](50) NULL,
	[chest_setting3na] [int] NULL,
	[chest_setting4] [int] NULL,
	[chest_setting4guid] [varchar](50) NULL,
	[chest_setting4na] [int] NULL,
	[chest2_machine] [varchar](max) NULL,
	[chest2_manufacture] [varchar](50) NULL,
	[chest2_setting1] [int] NULL,
	[chest2_setting1guid] [varchar](50) NULL,
	[chest2_setting1na] [int] NULL,
	[chest2_setting2] [int] NULL,
	[chest2_setting2guid] [varchar](50) NULL,
	[chest2_setting2na] [int] NULL,
	[chest2_setting3] [int] NULL,
	[chest2_setting3guid] [varchar](50) NULL,
	[chest2_setting3na] [int] NULL,
	[chest2_setting4] [int] NULL,
	[chest2_setting4guid] [varchar](50) NULL,
	[chest2_setting4na] [int] NULL,
	[knee_machine] [varchar](max) NULL,
	[knee_manufacture] [varchar](50) NULL,
	[knee_setting1] [int] NULL,
	[knee_setting1guid] [varchar](50) NULL,
	[knee_setting1na] [int] NULL,
	[knee_setting2] [int] NULL,
	[knee_setting2guid] [varchar](50) NULL,
	[knee_setting2na] [int] NULL,
	[knee_setting3] [int] NULL,
	[knee_setting3guid] [varchar](50) NULL,
	[knee_setting3na] [int] NULL,
	[knee_setting4] [int] NULL,
	[knee_setting4guid] [varchar](50) NULL,
	[knee_setting4na] [int] NULL,
	[leg_machine] [varchar](max) NULL,
	[leg_manufacture] [varchar](50) NULL,
	[leg_setting1] [int] NULL,
	[leg_setting1guid] [varchar](50) NULL,
	[leg_setting1na] [int] NULL,
	[leg_setting2] [int] NULL,
	[leg_setting2guid] [varchar](50) NULL,
	[leg_setting2na] [int] NULL,
	[leg_setting3] [int] NULL,
	[leg_setting3guid] [varchar](50) NULL,
	[leg_setting3na] [int] NULL,
	[leg_setting4] [int] NULL,
	[leg_setting4guid] [varchar](50) NULL,
	[leg_setting4na] [int] NULL,
	[legcurl_machine] [varchar](max) NULL,
	[legcurl_manufacture] [varchar](50) NULL,
	[legcurl_setting1] [int] NULL,
	[legcurl_setting1guid] [varchar](50) NULL,
	[legcurl_setting1na] [int] NULL,
	[legcurl_setting2] [int] NULL,
	[legcurl_setting2guid] [varchar](50) NULL,
	[legcurl_setting2na] [int] NULL,
	[legcurl_setting3] [int] NULL,
	[legcurl_setting3guid] [varchar](50) NULL,
	[legcurl_setting3na] [int] NULL,
	[legcurl_setting4] [int] NULL,
	[legcurl_setting4guid] [varchar](50) NULL,
	[legcurl_setting4na] [int] NULL,
	[modleg_machine] [varchar](max) NULL,
	[modleg_manufacture] [varchar](50) NULL,
	[modleg_setting1] [int] NULL,
	[modleg_setting1guid] [varchar](50) NULL,
	[modleg_setting1na] [int] NULL,
	[modleg_setting2] [int] NULL,
	[modleg_setting2guid] [varchar](50) NULL,
	[modleg_setting2na] [int] NULL,
	[modleg_setting3] [int] NULL,
	[modleg_setting3guid] [varchar](50) NULL,
	[modleg_setting3na] [int] NULL,
	[modleg_setting4] [int] NULL,
	[modleg_setting4guid] [varchar](50) NULL,
	[modleg_setting4na] [int] NULL,
	[overhead_machine] [varchar](max) NULL,
	[overhead_manufacture] [varchar](50) NULL,
	[overhead_setting1] [int] NULL,
	[overhead_setting1guid] [varchar](50) NULL,
	[overhead_setting1na] [int] NULL,
	[overhead_setting2] [int] NULL,
	[overhead_setting2guid] [varchar](50) NULL,
	[overhead_setting2na] [int] NULL,
	[overhead_setting3] [int] NULL,
	[overhead_setting3guid] [varchar](50) NULL,
	[overhead_setting3na] [int] NULL,
	[overhead_setting4] [int] NULL,
	[overhead_setting4guid] [varchar](50) NULL,
	[overhead_setting4na] [int] NULL,
	[pull_machine] [varchar](max) NULL,
	[pull_manufacture] [varchar](50) NULL,
	[pull_setting1] [int] NULL,
	[pull_setting1guid] [varchar](50) NULL,
	[pull_setting1na] [int] NULL,
	[pull_setting2] [int] NULL,
	[pull_setting2guid] [varchar](50) NULL,
	[pull_setting2na] [int] NULL,
	[pull_setting3] [int] NULL,
	[pull_setting3guid] [varchar](50) NULL,
	[pull_setting3na] [int] NULL,
	[pull_setting4] [int] NULL,
	[pull_setting4guid] [varchar](50) NULL,
	[pull_setting4na] [int] NULL,
	[seatrow_machine] [varchar](max) NULL,
	[seatrow_manufacture] [varchar](50) NULL,
	[seatrow_setting1] [int] NULL,
	[seatrow_setting1guid] [varchar](50) NULL,
	[seatrow_setting1na] [int] NULL,
	[seatrow_setting2] [int] NULL,
	[seatrow_setting2guid] [varchar](50) NULL,
	[seatrow_setting2na] [int] NULL,
	[seatrow_setting3] [int] NULL,
	[seatrow_setting3guid] [varchar](50) NULL,
	[seatrow_setting3na] [int] NULL,
	[seatrow_setting4] [int] NULL,
	[seatrow_setting4guid] [varchar](50) NULL,
	[seatrow_setting4na] [int] NULL,
	[shoulder_machine] [varchar](max) NULL,
	[shoulder_manufacture] [varchar](50) NULL,
	[shoulder_setting1] [int] NULL,
	[shoulder_setting1guid] [varchar](50) NULL,
	[shoulder_setting1na] [int] NULL,
	[shoulder_setting2] [int] NULL,
	[shoulder_setting2guid] [varchar](50) NULL,
	[shoulder_setting2na] [int] NULL,
	[shoulder_setting3] [int] NULL,
	[shoulder_setting3guid] [varchar](50) NULL,
	[shoulder_setting3na] [int] NULL,
	[shoulder_setting4] [int] NULL,
	[shoulder_setting4guid] [varchar](50) NULL,
	[shoulder_setting4na] [int] NULL,
	[triceps_machine] [varchar](max) NULL,
	[triceps_manufacture] [varchar](50) NULL,
	[triceps_setting1] [int] NULL,
	[triceps_setting1guid] [varchar](50) NULL,
	[triceps_setting1na] [int] NULL,
	[triceps_setting2] [int] NULL,
	[triceps_setting2guid] [varchar](50) NULL,
	[triceps_setting2na] [int] NULL,
	[triceps_setting3] [int] NULL,
	[triceps_setting3guid] [varchar](50) NULL,
	[triceps_setting3na] [int] NULL,
	[triceps_setting4] [int] NULL,
	[triceps_setting4guid] [varchar](50) NULL,
	[triceps_setting4na] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[frm_RESL] ADD  DEFAULT (newid()) FOR [recordthread]
GO

ALTER TABLE [dbo].[frm_RESL] ADD  DEFAULT (getdate()) FOR [d_inserted]
GO


