SELECT 
	TOP( 7 )
	 DELETED	
	,DELETEDBY	
	,DELETEREASON 
	,D_DELETED	
	,D_INSERTED
	,EXERCISEDESCRIPTION AS pname
	,EXERCISEGUID
	,EXERCISEORDER	AS urlparam 
	,FORMVARIABLENAME AS prefix 
	,INSERTEDBY
	,RECID
FROM	
	equipmentTrackingExercises
WHERE
	EXERCISEORDER NOT IN ( 15, 16 )
AND 
	EXERCISEORDER > :ord 
ORDER BY EXERCISEORDER ASC
