SELECT 
	 DELETED	
	,DELETEDBY	
	,DELETEREASON 
	,D_DELETED	
	,D_INSERTED
	,EXERCISEDESCRIPTION AS pname
	,EXERCISEGUID
	,EXERCISEORDER	AS urlparam 
	,FORMVARIABLENAME AS prefix 
	,INSERTEDBY
	,RECID
FROM	
	equipmentTrackingExercises
WHERE
	EXERCISEORDER = :id 
