SELECT TOP (1)
	 rec_id as c_rec_id
	,recordthread as c_recordthread
	,d_inserted as c_d_inserted
	,insertedBy as c_insertedBy
	,deleted as c_deleted
	,deleteReason as c_deleteReason
	,participantGUID as c_participantGUID
	,visitGUID as c_visitGUID
	,d_visit as c_d_visit
	,staffID as c_staffID
	,dayofwk as c_dayofwk
	,stdywk as c_stdywk
	,weight as c_weight
	,Hrworking as c_Hrworking
	,m10_exhr as c_m10_exhr
	,m10_exoth1 as c_m10_exoth1
	,m10_exoth2 as c_m10_exoth2
	,m10_exprctgrade as c_m10_exprctgrade
	,m10_exrpm as c_m10_exrpm
	,m10_exspeed as c_m10_exspeed
	,m10_exwatres as c_m10_exwatres
	,m15_exhr as c_m15_exhr
	,m15_exoth1 as c_m15_exoth1
	,m15_exoth2 as c_m15_exoth2
	,m15_exprctgrade as c_m15_exprctgrade
	,m15_exrpm as c_m15_exrpm
	,m15_exspeed as c_m15_exspeed
	,m15_exwatres as c_m15_exwatres
	,m20_exhr as c_m20_exhr
	,m20_exoth1 as c_m20_exoth1
	,m20_exoth2 as c_m20_exoth2
	,m20_exothafct as c_m20_exothafct
	,m20_exprctgrade as c_m20_exprctgrade
	,m20_exrpe as c_m20_exrpe
	,m20_exrpm as c_m20_exrpm
	,m20_exspeed as c_m20_exspeed
	,m20_exwatres as c_m20_exwatres
	,m25_exhr as c_m25_exhr
	,m25_exoth1 as c_m25_exoth1
	,m25_exoth2 as c_m25_exoth2
	,m25_exprctgrade as c_m25_exprctgrade
	,m25_exrpm as c_m25_exrpm
	,m25_exspeed as c_m25_exspeed
	,m25_exwatres as c_m25_exwatres
	,m30_exhr as c_m30_exhr
	,m30_exoth1 as c_m30_exoth1
	,m30_exoth2 as c_m30_exoth2
	,m30_exprctgrade as c_m30_exprctgrade
	,m30_exrpm as c_m30_exrpm
	,m30_exspeed as c_m30_exspeed
	,m30_exwatres as c_m30_exwatres
	,m35_exhr as c_m35_exhr
	,m35_exoth1 as c_m35_exoth1
	,m35_exoth2 as c_m35_exoth2
	,m35_exprctgrade as c_m35_exprctgrade
	,m35_exrpm as c_m35_exrpm
	,m35_exspeed as c_m35_exspeed
	,m35_exwatres as c_m35_exwatres
	,m40_exhr as c_m40_exhr
	,m40_exoth1 as c_m40_exoth1
	,m40_exoth2 as c_m40_exoth2
	,m40_exprctgrade as c_m40_exprctgrade
	,m40_exspeed as c_m40_exspeed
	,m40_exwatres as c_m40_exwatres
	,m40_exrpm as c_m40_exrpm
	,m45_exhr as c_m45_exhr
	,m45_exoth1 as c_m45_exoth1
	,m45_exoth2 as c_m45_exoth2
	,m45_exOthafct as c_m45_exOthafct
	,m45_exprctgrade as c_m45_exprctgrade
	,m45_exrpe as c_m45_exrpe
	,m45_exrpm as c_m45_exrpm
	,m45_exspeed as c_m45_exspeed
	,m45_exwatres as c_m45_exwatres
	,m5_exhr as c_m5_exhr
	,m5_exoth1 as c_m5_exoth1
	,m5_exoth2 as c_m5_exoth2
	,m5_exprctgrade as c_m5_exprctgrade
	,m5_exrpm as c_m5_exrpm
	,m5_exspeed as c_m5_exspeed
	,m5_exwatres as c_m5_exwatres
	,m3_rechr as c_m5_rechr
	,m3_recoth1 as c_m5_recoth1
	,m3_recoth2 as c_m5_recoth2
	,m3_recprctgrade as c_m5_recprctgrade
	,m3_recrpm as c_m5_recrpm
	,m3_recspeed as c_m5_recspeed
	,m3_recwatres as c_m5_recwatres
	,mchntype as c_mchntype
	,MthlyBPDia as c_MthlyBPDia
	,MthlyBPSys as c_MthlyBPSys
	,nomchntype as c_nomchntype
	,nxtsesn_dt as c_nxtsesn_dt
	,othMchn1 as c_othMchn1
	,othMchn2 as c_othMchn2
	,reasnmisd as c_reasnmisd
	,Sessionmisd as c_Sessionmisd
	,Sp_mchntype as c_Sp_mchntype
	,sp_reasnmisd as c_sp_reasnmisd
	,trgthr1 as c_trgthr1
	,trgthr2 as c_trgthr2
	,typedata as c_typedata
	,wrmup_hr as c_wrmup_hr
	,wrmup_oth1 as c_wrmup_oth1
	,wrmup_oth2 as c_wrmup_oth2
	,wrmup_othafct as c_wrmup_othafct
	,wrmup_prctgrade as c_wrmup_prctgrade
	,wrmup_rpe as c_wrmup_rpe
	,wrmup_rpm as c_wrmup_rpm
	,wrmup_speed as c_wrmup_speed
	,wrmup_watres as c_wrmup_watres
	,breaks as c_breaks
FROM 
	frm_EETL	
WHERE 
	participantGUID = :pid
AND 
	stdywk = :stdywk
AND 
	dayofwk = :dayofwk
